services:
  - type: web
    name: kindred-ui
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host=0.0.0.0 --port=10000
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
